# Generated by Django 3.1.2 on 2020-11-05 23:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_application', '0003_remove_jobapplication_job_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobApplication',
            new_name='Application',
        ),
    ]
