# Generated by Django 3.1.2 on 2020-11-05 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job_application', '0004_auto_20201105_2347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Application',
            new_name='JobApplication',
        ),
    ]
