# Generated by Django 3.1.2 on 2020-11-13 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0005_auto_20201105_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.CharField(max_length=60)),
                ('job_position', models.CharField(max_length=60)),
                ('status', models.CharField(choices=[('O', 'Open'), ('C', 'Closed')], default='O', max_length=1)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('S', 'Sumbmitted'), ('U', 'Under Consideration'), ('N', 'No Longer Under Consideration')], default='S', max_length=1),
        ),
    ]
