# Generated by Django 3.1.2 on 2020-11-13 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0006_auto_20201113_2234'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='submitted_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='job_application.jobposting'),
        ),
    ]
