# Generated by Django 3.1.2 on 2020-11-20 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0007_jobapplication_submitted_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='submitted_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_application.jobposting'),
        ),
    ]
