# Generated by Django 3.1.2 on 2020-11-20 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0008_auto_20201120_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='submitted_to',
            new_name='company',
        ),
    ]
