# Generated by Django 3.1.3 on 2020-12-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20201201_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
    ]
