# Generated by Django 3.1.3 on 2020-12-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_auto_20201201_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.IntegerField(verbose_name=10),
        ),
    ]
