# Generated by Django 3.1.3 on 2020-12-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0005_remove_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
