# Generated by Django 3.1.3 on 2020-12-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank='true', max_length=100),
        ),
    ]
